[window]
decorations = "None"

opacity = 0.95

padding.x = 10
padding.y = 10

decorations_theme_variant = "Dark" #"Light"  

startup_mode = "Maximized"# | "Fullscreen" | "SimpleFullscreen" | "Windowed"

[font]

normal.family = "Source Code Pro"
bold.family = "Source Code Pro"
italic.family = "Source Code Pro"
bold_italic.family = "Source Code Pro"

size = 22.0

