[window]
decorations = "None"

opacity = 0.9

padding.x = 10
padding.y = 10

decorations_theme_variant = "Dark" #"Light"  

[font]

normal.family = "Source Code Pro"
bold.family = "Source Code Pro"
italic.family = "Source Code Pro"
bold_italic.family = "Source Code Pro"

size = 24.0
